name: makepkg

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: archlinux:base-devel

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
        with:
          ref: archpkg

      - name: Call makepkg
        run: makepkg
      
      - uses: actions/upload-artifact@v4.3.1
        with:
          path: "*.pkg.tar.zst"
